# Generated by Django 5.2.1 on 2025-06-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_dislike_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='items/previews/', verbose_name='Превью'),
        ),
    ]
