# Generated by Django 5.2.1 on 2025-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кредит'),
            preserve_default=False,
        ),
    ]
