# Generated by Django 5.2.1 on 2025-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_item_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кредит'),
        ),
    ]
